name: 💡 Feature Request
description: Suggest a new idea or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Help us understand your idea by completing the sections below.

  - type: textarea
    id: problem
    attributes:
      label: What's the problem this solves?
      description: Describe the need or issue that this feature addresses.
      placeholder: It's hard to do ___ because ___
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your idea or feature in detail.
      placeholder: I think the app should do ___ so that ___
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you thought of other ways to solve this?
      placeholder: Other approaches, plugins, or workarounds you've tried.
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Additional Notes
      description: Links, mockups, references, or anything else helpful.
    validations:
      required: false
